### ISSUE TITLE
Update UI/UX to Handle New Auth Mechanics

### ISSUE THREAD

**Issue by gregbrunk** [astronomerio/orbit-ui#37]
- [ ] Enable username / pw auth
- [x] Recreate auth flow for auth0
- [x] Enable CLI auth flow via query param
- [x] Redirect airflow (and same origin referrers) on login
- [x] Ensure protected routes are working correctly (eg. delete / expire token)

_placeholder ticket to support any changes in Orbit that result from:_
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/36
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/37
- https://app.zenhub.com/workspace/o/astronomerio/houston-api/issues/38

**Comment by schnie** [comment]
@pcmaffey how we lookin? Would love to get 0.3.3 released today/tonight.

Where did we end up yesterday on the email flows?

cc @cwurtz

**Comment by pcmaffey** [comment]
So doing a quick rundown, here's the status. @cwurtz feel free to update 

- [ ]  A user can signup & login with email/pw

- [ ]  On signup, if a token isn't returned, they're redirected to a page telling them to check their email to confirm

- [ ] On signup, the api creates the user and instead of creating a token, sends an email with verification link to route `/verify?token=asbafd`

- [ ] A user cannot login / createToken without a verified email

- [ ] A user can reset their password by entering their email address and getting sent an email with link to route `/reset-password?token=asdfasdf`

- [ ]  A mutation to update password
